name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy to server
      env:
        SERVER_IP: 174.138.29.36
        SERVER_USER: root
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      run: |
        sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
          cd /projects/braincount
          git pull https://github.com/snigdho48/braincountnew.git 
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py makemigrations api
          python manage.py migrate
          mkdir -p static media
          python manage.py collectstatic --noinput
          systemctl daemon-reload
          systemctl restart gunicorn-braincount
          systemctl restart nginx
          chown -R www-data:www-data static
          chown -R $USER:www-data media
          sudo mkdir -p /var/run/daphne
          sudo chown www-data:www-data /var/run/daphne
          sudo systemctl restart daphne.service
          chmod -R 755 static
          chmod -R 755 media
          chmod 755 /projects
          python manage.py celery worker -l info
          python manage.py celery beat -l info
          celery -A braincountBackend beat -l info

          echo "Deployment successful"
        EOF
